#!/bin/bash
# Phase 5 Scheduler Integration - Staging Deployment Script
# Execute this script to deploy Phase 5 to staging environment

set -e  # Exit on error

echo "=========================================="
echo "Phase 5 - Staging Deployment"
echo "=========================================="
echo ""

# Step 1: Verify environment
echo "[STEP 1] Verifying staging environment..."
python -c "from app.config import settings; print(f'Database: {settings.database_url[:30]}...')" || {
    echo "ERROR: Cannot connect to database. Check SUPABASE_URL and SUPABASE_KEY"
    exit 1
}
echo "[OK] Environment verified"
echo ""

# Step 2: Run all unit tests
echo "[STEP 2] Running unit test suite (24 tests)..."
pytest tests/test_scheduler_integration.py -v --tb=short || {
    echo "ERROR: Unit tests failed. Do not proceed with deployment."
    exit 1
}
echo "[OK] All 24 unit tests passing"
echo ""

# Step 3: Create database backup
echo "[STEP 3] Database backup (MANUAL STEP REQUIRED)..."
echo ""
echo "Before proceeding, please backup your staging database:"
echo ""
echo "  Option A (Supabase Dashboard):"
echo "    1. Go to Database > Backups"
echo "    2. Click 'Create backup'"
echo "    3. Wait for backup to complete"
echo ""
echo "  Option B (Command line):"
echo "    pg_dump --format custom -f staging_backup_\$(date +%Y%m%d_%H%M%S).bak [DATABASE_URL]"
echo ""
read -p "Press ENTER when backup is complete..."
echo "[OK] Database backup confirmed"
echo ""

# Step 4: Apply database migration
echo "[STEP 4] Applying database migration..."
echo ""
echo "Execute the following SQL on your staging database:"
echo ""
echo "========== SQL MIGRATION BELOW =========="
cat database/migrations/006_scheduler_integration.sql
echo "========== END SQL MIGRATION ==========="
echo ""
echo "Options to execute:"
echo ""
echo "  Option A (Supabase SQL Editor):"
echo "    1. Go to Supabase Dashboard > SQL Editor"
echo "    2. Click 'New Query'"
echo "    3. Copy and paste the SQL above"
echo "    4. Click 'Run'"
echo ""
echo "  Option B (Command line):"
echo "    psql -h [HOST] -U [USER] -d [DATABASE] -f database/migrations/006_scheduler_integration.sql"
echo ""
read -p "Press ENTER when migration is applied..."
echo "[OK] Database migration applied"
echo ""

# Step 5: Validate database schema
echo "[STEP 5] Validating database schema..."
echo ""
echo "Manually verify tables were created:"
echo "  SELECT table_name FROM information_schema.tables"
echo "  WHERE table_schema = 'public' AND table_name LIKE 'migration%';"
echo ""
echo "Expected tables:"
echo "  - migration_schedules"
echo "  - migration_batches"
echo "  - migration_logs"
echo ""
read -p "Press ENTER when you have verified the tables..."
echo "[OK] Database schema validated"
echo ""

# Step 6: Deploy application code
echo "[STEP 6] Deploying application code..."
echo ""
echo "Option A (Git push to staging):"
echo "  git push origin main"
echo ""
echo "Option B (Manual deployment):"
echo "  1. Copy app/ and database/ directories to staging server"
echo "  2. Run: uv sync"
echo "  3. Restart application service"
echo ""
read -p "Press ENTER when code is deployed..."
echo "[OK] Application code deployed"
echo ""

# Step 7: Verify scheduler initialization
echo "[STEP 7] Verifying scheduler initialization..."
echo ""
echo "Check application logs for:"
echo '  "[Phase 5] 정기 문서 마이그레이션 스케줄러 초기화 완료"'
echo ""
echo "Or check logs via:"
echo "  - Railway: railway logs"
echo "  - Render: render logs  "
echo "  - Direct SSH: tail -f /var/log/app.log"
echo ""
read -p "Press ENTER when you have verified scheduler initialization..."
echo "[OK] Scheduler initialization verified"
echo ""

# Step 8: Run API validation tests
echo "[STEP 8] Running API validation tests..."
echo ""
echo "From staging environment, run:"
echo "  pytest tests/test_scheduler_integration.py -v"
echo ""
echo "Expected result: 24/24 tests PASSING"
echo ""
read -p "Press ENTER when tests are complete..."
echo "[OK] API tests validated"
echo ""

# Step 9: Manual API endpoint testing
echo "[STEP 9] Testing API endpoints..."
echo ""
echo "Run the following curl commands from staging:"
echo ""
echo "Create Schedule:"
echo "  curl -X POST http://staging-api.local/api/migration/schedules \\"
echo "    -H 'Authorization: Bearer [TOKEN]' \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"name\": \"Test\", \"cron_expression\": \"0 8 * * *\", \"enabled\": true}'"
echo ""
echo "Get Schedules:"
echo "  curl -X GET http://staging-api.local/api/migration/schedules \\"
echo "    -H 'Authorization: Bearer [TOKEN]'"
echo ""
read -p "Press ENTER when endpoint tests are complete..."
echo "[OK] API endpoints tested"
echo ""

# Step 10: Monitoring setup
echo "[STEP 10] Setting up monitoring..."
echo ""
echo "Monitor these metrics for 30 minutes:"
echo ""
echo "  - Scheduler startup time (target: < 2s)"
echo "  - API response time (target: < 200ms)"
echo "  - Error rate (target: < 0.1%)"
echo "  - Batch processing time (target: < 30s for 100 docs)"
echo ""
echo "Commands to monitor:"
echo "  tail -f [app_logs] | grep -E 'Scheduler|Batch|error'"
echo ""
echo "If any errors occur, check:"
echo "  - docs/operations/phase5-staging-deployment-guide.md (Troubleshooting section)"
echo "  - Rollback plan: Database backup exists, use if needed"
echo ""
read -p "Press ENTER to complete deployment..."
echo "[OK] Monitoring setup complete"
echo ""

# Summary
echo "=========================================="
echo "DEPLOYMENT COMPLETE"
echo "=========================================="
echo ""
echo "Phase 5 Scheduler Integration has been deployed to staging."
echo ""
echo "Next Steps:"
echo "  1. Continue monitoring for 30 minutes"
echo "  2. If all checks pass, update deployment status"
echo "  3. Plan production deployment for 2026-04-25"
echo "  4. Review any issues found in staging"
echo ""
echo "Documentation:"
echo "  - Full guide: docs/operations/phase5-staging-deployment-guide.md"
echo "  - Rollback plan: See guide Appendix"
echo "  - Test results: tests/test_scheduler_integration.py"
echo ""
echo "For issues or questions:"
echo "  - Check logs: tail -f [app_logs]"
echo "  - Review guide: docs/operations/phase5-staging-deployment-guide.md"
echo "  - Escalate if needed (Contact: #tenopa-technical)"
echo ""
